# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://adamtongji.github.io
date_format: "ordinal"
title: "Shaliu's Blog"
subtitle: "用心感受数据，用生信治病救人"
description: "傅沙镠的个人博客"
keywords: Shaliu, adam, tongji, bioinformatics
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shaliu Fu
organization: tongji univ.
organization_url: http://www.tongji.edu.cn
github_username: adamtongji
location: Shanghai, China
email: adam.tongji@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner:  
    repo: blog-comments
    oauth:
        client_id:  
        client_secret:  
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: adamtongji
    repo: blog-comments
    clientID: 6f852fdd39e4208dc7c9
    clientSecret: 58383335a24dc750975505c224163751061344e3
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
